command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "4b9b953939869799"
    #valueFrom: "sql-warehouse"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: STREAMLIT_SERVER_ENABLE_WEBSOCKET_COMPRESSION
    value: "true"